### ISSUE TITLE
[DEV] Create a plugin that populates host information for use with jinja templates

### ISSUE THREAD

**Issue by alexlovelltroy** [OpenCHAMI/configurator#16]
This task is to get us enough information to generate host-specific files.

example :

```yaml
hostnames:
interfaces:
  - eth0
     name:
     mac: 
     ip:
     desc:
     netmask:
     hostnames:
  - eth1
     name:
     mac: 
     ip:
     description:
     netmask:
     hostnames:
  - eth2
     name:
     mac: 
     ip:
     description:
     netmask:
     hostnames:
```
